import Head from 'next/head'
import Footer from '../app/components/modules/Footer/Footer';
import Header from '../app/components/modules/Header/Header'
import Hero from '../app/components/modules/Hero/Hero'
import Products from '../app/components/modules/Products/Products';
import styles from '../styles/Home.module.scss';

export default function Home({ products }) {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Products products={products}/>
      <Footer />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://still-temple-20368.herokuapp.com/products');
  const data = await res.json();

  return {
    props: { products: data }
  }
}